window.languageData = {
  "en": {
    "home": "Home",
    "service": "Services",
    "Projects": "Projects",
    "Objectives": "Our Objectives",
    "Contact": "Contact us",

    "phone": "+20221808809",
    "address": "7 Mohamed Mahmoud Ezzat St, Hegaz, Cairo, Egypt",
    "AMHZ": "AMHZ Group",
    "About": "About",
    "ourcompany": "Our company",
    "ourcompanyHeader": "AMH Group Expertise in All Sectors",
    "years": "Years’ Experience in IT",
    "success": "More About Our Success Stories",
    "number": "38",
    "aboutAMHZ": "The journey began in 2007 when AMH Group for Contracting and General Supplies was founded by its founder, Engineer Mohamed Ali Saad. The company gained prominence and distinction among others, earning recognition from government institutions, banks, and success partners due to its integrity in dealings and client trust. This led to an expansion in business activities, evolving into AMH International Group, which now comprises five specialized subsidiary companies in the fields of general contracting, software technology, agricultural consultancy, medical supplies, and import and export.",
    "companyButton": "Discover now",
    "features": "Extra Features",
    "projects": "Our projects",
    "proudProjects": "Proud projects",
    "makeus": "make us excel",
    "ServiceDetails": "Service Details",

    "ContractingServices": "Contracting Services",
    "ContractingReview": "Over the past years, AMH Contracting has risen to prominence, distinguished by offering a range of excellent services of high quality that authentically and expertly reflect the company's level of professionalism...",
    "ContractingButton": "Discover now",
    "contentContracting": "AMH Contracting has advanced over the past years, as the group has distinguished itself by providing a package of excellent services with high quality that expresses with originality and mastery the professional level that the company has reached and is developing at a rapid pace in order to achieve strategic goals in addition to the field of general contracting, for example:",
    "item1Contracting": "Integrated works",
    "item2Contracting": "Finishing works",
    "item3Contracting": "Road and paving works",
    "item4Contracting": "Infrastructure works",
    "item5Contracting": "Landscape, softscape and hardscape works",
    "item6Contracting": "Sewage treatment plants and drinking water desalination works",

    "AgriculturalServices": "Agricultural Services",
    "AgriculturalReview": "Our strategy focuses on providing comprehensive information that farmers need to continue production, assisting them in developing their scientific skills, and improving the agricultural situation...",
    "AgriculturalButton": "Discover now",
    "contentAgricultural": "Our strategy works to provide comprehensive information that farmers need in order to continue production, and to help them develop the scientific skills they possess, to improve the agricultural situation, and includes the following:",
    "item1Agricultural": "Inputs needed to complete the farming process to obtain outputs with minimal investment",
    "item2Agricultural": "Crops that can be grown and crops that cannot be grown",
    "item3Agricultural": "Determine the type of crop that can be grown according to the type of agricultural land soil.",
    "item4Agricultural": "Providing accurate and timely information and strengthening the links between consumer markets to absorb crops, in order to ensure continuous and regular profit increases throughout the year",
    "item5Agricultural": "Farm management",
    "item6Agricultural": "Import of food raw materials",
    "item7Agricultural": "Export food products",

    "ImportExportServices": "Import and Export Services",
    "ImportReview": " AMH Import and Export has recently added general trading, impor and export, and commercial agency activities to its range of operations, expanding its services to include various import services...",
    "ImportExportButton": "Discover now",
    "ImportAndExportContent": "AMH Import & Export has recently added general trade, import and export, and commercial agencies to its business package, to provide many import services, specialized customs, customs clearance services, and a distinguished package of services in importing and exporting products to and from countries around the world, such as:",
    "item1ImportExport": "Supply Chain Management",
    "item2ImportExport": "Planning",
    "item3ImportExport": "Import of raw materials",
    "item4ImportExport": "Providing transportation resources as an intermediary from country to country Providing resources",
    "item5ImportExport": "Agent - Exclusive source for some factories",
    "item6ImportExport": "International Marketing",
    "item7ImportExport": "Delivery and Logistics",
    "item8ImportExport": "Export products",
    "item9ImportExport": "Providing resources",

    "TechnologyServices": "Technology Services",
    "TechnologyReview": "Providing the Egyptian and Arab markets with integrated software solutions to bridge the gap between market aspirations and the high costs of solutions offered by international companies...",
    "TechnologyButton": "Discover now",
    "TechnologyContent": "Providing the needs of the Egyptian and Arab markets for all integrated software solutions and bridging the gap between what the market aspires to and the high prices of solutions provided by international companies.",
    "item1Technology": "DIGITAL TRANSFORMATION",
    "item2Technology": "BUSINESS PARTNER",
    "item3Technology": "Distribution of software for large companies and existing software",

    "MedicalServices": "Medical Services",
    "MedicalReview": "AMH Medical offers specialized services in cardiology, vascular diseases, dialysis, urology, and gastrointestinal endoscopy equipment. We work on making our products available in hospitals across Egypt.",
    "MedicalButton": "Discover now",
    "MedicalContent": "AMH Medical provides specialized services in Cardiology, Vascular, Hemodialysis, Urology, and Gastrointestinal Endoscopy devices. We work to provide our products in all hospitals in Egypt, emergency cases, home care environments, specialized tools used during intensive care and surgery, post-operative care and support for chronic diseases.",
    "item1Medical": "Surgical instruments",
    "item2Medical": "Sterilizers",
    "item3Medical": "Personal supplies",
    "item4Medical": "Operating room preparation",

    "foundations": "The most important foundations of our work",
    "foundationHeader": "Loyalty",
    "foundationContent": "To our beloved country, Egypt, which we seek to serve and achieve its prosperity.",

    "QualityHeader": "Quality",
    "QualityContent": "The ticket to our dreams and ambitions.",


    "ResilienceHeader": "Resilience",
    "ResilienceContent": "Our confidence in ourselves enables us to harness difficulties to make them accessible.",

    "ResponsibilityHeader": "Responsibility",
    "ResponsibilityContent": "Towards fulfilling our commitments to the highest quality standards.",

    "backHeader": "Our Companies",
    "frontHeader": "Companies",
    "ConstructionHeader": "AMH Construction",
    "ConstructionContent": "It is a national Egyptian company that always seeks leadership in the field of general contracting and supplies...",
    "ConstructionTotalContent": "It is an Egyptian national company that always seeks leadership in the field of general contracting and supplies. The company has specialized in leveling, excavation, cutting, road and paving works, infrastructure, general contracting works, finishing and decorations. Specializing in the construction, preparation and equipment of buildings and general supply works for the construction and building sector, finishing and decorations, security devices, landscape and hardscape works. Accuracy in implementation, speed of implementation, respect for the Egyptian cadre of roads and construction by following standard specifications, and the company's ability to coordinate sites and not accept any defects in the work.",
    "AgriculturalHeader": "AMH Agricultural",
    "AgriculturalContent": "A company specialized in managing large farms with the latest agricultural technology. Our latest projects are implemented in cooperation with the Armed Forces...",
    "AgriculturalTotalContent": "A company specialized in managing large farms with the latest agricultural technology. Our latest projects are implemented in cooperation with the Armed Forces. AMH Agricultural Company works on reclaiming agricultural lands, unifying the standards for trading agricultural production for consumption purposes in the local market, and maintaining the quality of agricultural crops to produce healthy and safe food. The company entered the labor market in 2020, and began its agricultural journey with an important and huge project, which is the reclamation of the new Al-Mu'ahda farm (with an area of ​​185 acres).",
    "ImportExportHeading": "AMH Import And Export",
    "ImportExportContent": "A company specialized in the field of import and export, aiming to achieve our vision in supporting the Egyptian economy and increasing the ability to provide distinguished international trade services...",
    "ImportExportTotalContent": "A company specialized in the field of import and export, aiming to achieve our vision in supporting the Egyptian economy and increasing the ability to provide distinguished international trade services. AMH Import and Export has obtained many commercial agencies as an authorized and exclusive distributor of the best international products in many sectors.",
    "TechnologyHeading": "AMH Technology",
    "TechnologyContent": ",An Egyptian joint stock company working in the field of integrated smart software solutions through a group of the best software engineers, and under ambitious and open management ...",
    "TechnologyTotalContent": "An Egyptian joint stock company working in the field of integrated smart software solutions through a group of the best software engineers, and under ambitious and open management, and we provide appropriate software solutions for everything the market requires. AMH Technology is keen to provide the highest quality standards to its customers, by using the latest global technologies in programming, training and management, and looks forward to participating in implementing digital transformation and applying the principles of governance and financial inclusion in Egypt and the Arab world, and also aims to compete with major global companies in the field of software.",
    "MedicalHeading": "AMH Medical",
    "MedicalContent": "It is one of the recently established companies within the \"AMHZ International Group\" which has a great experience in the field of contracting and trading...",
    "MedicalTotalContent": "It is one of the recently established companies within \"AMHZ International Group\" which has a great experience in the field of contracting and trading business, and now we have the best talented employees with great experience in medical field products. We started as a supplier of disposable medical products and our product range is gradually increasing. Egypt's distinguished location gives us the opportunity to reduce the cost of ordering because we are located in the middle of the world which reduces the cost of shipping, and Egypt has signed many trade agreements between many countries and regions which will reduce customs duties and reduce the final price of the required products.",

    "SouthernBinZayedAxis": "Southern Bin Zayed Project Axis",
    "project1Content": "",
    "CompanyDetails": "Company Details",
    "ProjectDetails": "Project Details",
    "EgyptFutureDabaaProject": "Egypt's Future Dabaa Project",
    "RoadworksAley": "Road works in Aley",
    "AhmadiyaStationProject": "Ahmadiya Station Project",
    "Sherbinstationproject": "Sherbin station project",
    "Road32Project": "Road 32 Project",
    "BinZayedAxisProject": "Bin Zayed Axis Project",

    "constructionProject": "Construction project",
    "SouthernBinZayedAxisContent": "The Southern Bin Zayed Project Axis is likely a strategic infrastructure or urban development initiative named after Sheikh Zayed bin Sultan Al Nahyan, reflecting the region's ongoing efforts to expand and modernize. ",
    "EgyptFutureDabaaProjectContent": "The Egypt's Future Dabaa Project refers to the Dabaa Nuclear Power Plant, a significant and strategic initiative in Egypt's energy sector. Located in the Dabaa area of the Matrouh Governorate on the Mediterranean coast, this project marks Egypt's first venture into nuclear energy.",
    "RoadworksAleyContent": "Road Works in Aley refers to infrastructure development and maintenance activities in the Aley District, located in the Mount Lebanon Governorate. This project likely involves the construction, expansion, or repair of roads and transportation networks within the area.",
    "AhmadiyaStationProjectContent": "The Ahmadiya Station Project likely refers to the development or upgrading of a transportation hub, possibly a train or metro station, in the Ahmadiya area. This project might involve constructing a new station or renovating an existing one to better serve commuters and improve connectivity in the region.",
    "SherbinstationprojectContent": "The Sherbin Station Project likely refers to the development or enhancement of a transportation station in Sherbin, a city in the Dakahlia Governorate of Egypt. This project could involve the construction of a new train or bus station or the renovation and modernization of an existing facility.",
    "Road32ProjectContent": "The Road 32 Project likely involves the construction, expansion, or rehabilitation of a significant roadway, designated as \"Road 32,\" in a particular region. This project would focus on improving transportation infrastructure, facilitating smoother traffic flow, and enhancing connectivity between key areas.",
    "BinZayedAxisProjectContent": "The Bin Zayed Axis Project likely refers to a major infrastructure initiative named after Sheikh Zayed bin Sultan Al Nahyan, aiming to create a key transportation or development corridor. This project would focus on building or upgrading a significant road, highway, or urban axis that connects important regions or districts.",
    "viewmore": "View more",

    "ourobjectives": "Our Objectives",
    "Achieve": "How We Achieve",
    "goal": "Our Goals",

    "goal1Header": "1. Establishing Strategic Partnerships",
    "goal1Content": "Building partnerships with leading companies in the local and international construction sector",
    "goal2Header": "2. Customer Satisfaction",
    "goal2Content": "Meeting and exceeding customer requirements with the highest standards in record time",
    "goal3Header": "3. National Service Integration",
    "goal3Content": "Incorporating the concept of national service into all the group's various projects",
    "goal4Header": "4. Development & Growth",
    "goal4Content": "Achieving the necessary development and growth to increase investment flow and profitability",
    "circleNumber1": "1",
    "circleNumber2": "2",
    "circleNumber3": "3",
    "circleNumber4": "4",
    "makeRequest": "To make requests for",
    "furtherinformation": "further information,",
    "socialchannels": "via our social channels.",
    "wejust": "We just need a couple of hours!",
    "nomore": "No more than 2 working days since receiving your issue ticket.",
    "submit": "Send message",
    "requiredfield": "This field is required.",

    "obtaining": "Obtaining further information by make a contact with our experienced IT staffs.",
    "available": "We’re available for 8 hours a day!",
    "contactto": "Contact to require a detailed analysis and assessment of your plan.",
    "reach": "Reach out now!",
    "werun": "We run all kinds of IT services that vow your",
    "suc": "success",
    "let'stalk": "Let's talk",
    "getinfo": "Get info",
    "ITServices": "IT Services Designed For",
    "HighlyTailored": "Highly Tailored IT Design, Management & Support Services.",
    "freeconsultation": "Free consultation",
    "howwework": "How we work",
  },
  "ar": {
    "home": "الصفحة الرئيسية",
    "service": "الخدمات",
    "Projects": "المشاريع",
    "Objectives": "أهدافنا",
    "Contact": "اتصل بنا",

    "phone": "+20221808809",
    "address": "7 شارع محمد محمود عزت، ميدان الحجاز، القاهرة، مصر",
    "AMHZ": "مجموعة AMHZ",
    "About": "من نحن",
    "ourcompany": "شركتنا",
    "ourcompanyHeader": "مجموعة AMH تتمتع بخبرة في كافة القطاعات",
    "years": "سنوات من الخبرة في مجال تكنولوجيا المعلومات",
    "success": "المزيد عن قصص نجاحنا",
    "number": "٣٨",
    "aboutAMHZ": "بدأت الرحلة في عام ٢٠٠٧ عندما تأسست مجموعة AMH للمقاولات والتوريدات العامة على يد مؤسسها المهندس محمد علي سعد. اكتسبت الشركة شهرة وتميزًا بين الآخرين، ونالت تقديرًا من المؤسسات الحكومية والبنوك وشركاء النجاح نظرًا لنزاهتها في التعامل وثقة العملاء. أدى ذلك إلى توسع في الأنشطة التجارية، وتطورت إلى مجموعة AMH الدولية، والتي تضم الآن خمس شركات فرعية متخصصة في مجالات المقاولات العامة وتكنولوجيا البرمجيات والاستشارات الزراعية والمستلزمات الطبية والاستيراد والتصدير.",
    "companyButton": "اكتشف الان",
    "features": "مميزات اضافية",
    "projects": "مشارعينا",

    "proudProjects": "المشاريع الفخورة",
    "makeus": "تجعلنا نتفوق",
    "ContractingServices": "خدمات المقاولات",
    "ContractingReview": "على مدى السنوات الماضية، برزت شركة AMH للمقاولات بشكل كبير، وتميزت بتقديم مجموعة من الخدمات الممتازة ذات الجودة العالية والتي تعكس بشكل أصيل وخبرة مستوى الاحترافية التي تتمتع بها الشركة...",
    "ContractingButton": "اكتشف الآن",
    "contentContracting": ":ارتقت أيه أم أتش للمقاولات خلال السنوات الماضية، حيث انفردت المجموعة بتقديم حزمة من الخدمات الممتازة وبجودة عالية تعبر بأصالة وإتقان عن ما وصلت إليه الشركة من مستوى احترافي وتتطور على قدم وساق في سبيل تحقيق الأهداف الإستراتيجية بجانب مجال المقاولات العامة وعلى سبيل المثال",
    "item1Contracting": "أعمال متكاملة",
    "item2Contracting": "أعمال التشطيبات",
    "item3Contracting": "أعمال الطرق والرصف",
    "item4Contracting": "أعمال البنية التحتية",
    "item5Contracting": "أعمال اللاند سكيب والسوفت سكيب والهارد سكيب",
    "item6Contracting": "أعمال محطات معالجة مياه الصرف الصحي وتحلية المياه الشرب",

    "AgriculturalServices": "الخدمات الزراعية",
    "AgriculturalReview": "تركز استراتيجيتنا على توفير المعلومات الشاملة التي يحتاجها المزارعون لمواصلة الإنتاج، ومساعدتهم في تطوير مهاراتهم العلمية، وتحسين الوضع الزراعي...",
    "AgriculturalButton": "اكتشف الآن",
    "contentAgricultural": "تعمل إستراتيجيتنا على توفير شامل للمعلومات التي يحتاجها المزارعون من أجل الاستمرارية في الإنتاج، ومساعدتهم على تنمية المهارات العلمية التي يمتلكونها، لتحسين الوضع الزراعي وتتضمن ما يلي:",
    "item1Agricultural": "المدخلات اللازمة لإتمام عملية الزراعة للحصول على مخرجات بأقل استثمارات",
    "item2Agricultural": "المحاصيل التي يمكن زراعتها والمحاصيل التي لا يمكن زراعتها",
    "item3Agricultural": "تحديد نوع المحصول الذي يمكن زراعته وفقا لنوع تربة الأرض الزراعية",
    "item4Agricultural": "إتاحة معلومات دقيقة في التوقيت المناسب وتعزيز الروابط بين الأسواق الاستهلاكية لاستيعاب المحاصيل، وذلك لضمان زيادة الربح بشكل مستمر ودوري على مدار العام",
    "item5Agricultural": "إدارة المزارع",
    "item6Agricultural": "استيراد مواد خام غذائية",
    "item7Agricultural": "تصدير منتجات غذائية",

    "ImportExportServices": "خدمات الاستيراد والتصدير",
    "ImportReview": "أضافت شركة AMH للاستيراد والتصدير مؤخرًا أنشطة التجارة العامة والاستيراد والتصدير والوكالات التجارية إلى نطاق عملياتها، ووسعت خدماتها لتشمل خدمات الاستيراد المختلفة...",
    "ImportExportButton": "اكتشف الآن",
    "ImportAndExportContent": "أضافت أيه أم أتش للاستيراد والتصدير نشاط التجارة العمومية، والاستيراد والتصدير، والتوكيلات التجارية مؤخرا إلى حزمة أعمالها، لتوفر العديد من الخدمات الاستيرادية، والجمركية المتخصصة، وخدمات التخليص الجمركي، وباقة خدمات متميزة في استيراد وتصدير المنتجات من وإلى دول العالم مثل:",
    "item1ImportExport": "إدارة سلاسل الإمداد",
    "item2ImportExport": "التخطيط",
    "item3ImportExport": "استيراد مواد خام",
    "item4ImportExport": "توفير مصادر نقل كوسيط من بلد لبلد توفير المصادر",
    "item5ImportExport": "وكيل - مصدر حصري لبعض المصانع",
    "item6ImportExport": "تسويق دولي",
    "item7ImportExport": "التسليم والخدمات اللوجيستية",
    "item8ImportExport": "تصدير منتجات",
    "item9ImportExport": "توفير المصادر",

    "TechnologyServices": "الخدمات التكنولوجية",
    "TechnologyReview": "- تزويد السوق المصري والعربي بحلول برمجية متكاملة لسد الفجوة بين تطلعات السوق والتكاليف المرتفعة للحلول التي تقدمها الشركات العالمية...",
    "TechnologyButton": "اكتشف الآن",
    "TechnologyContent": "توفير احتياجات السوق المصري والعربي لكل الحلول البرمجية المتكاملة وسد الفجوة بين ما يطمح إليه السوق وبين ارتفاع أسعار الحلول المقدمةمن الشركات العالمية.",
    "item1Technology": "التحول الرقمي",
    "item2Technology": "شريك الأعمال",
    "item3Technology": "توزيع برمجيات شركات كبرى وبرمجيات قائمة",

    "MedicalServices": "الخدمات الطبية",
    "MedicalReview": "تقدم شركة AMH Medical خدمات متخصصة في مجال أمراض القلب والأوعية الدموية وغسيل الكلى والمسالك البولية وأجهزة مناظير الجهاز الهضمي. ونعمل على توفير منتجاتنا في المستشفيات في جميع أنحاء مصر.",
    "MedicalButton": "اكتشف الآن",
    "MedicalContent": "تقدم ايه إم اتش ميديكال خدمات متخصصة في أمراض القلب، والأوعية الدموية، وغسيل الكلى، والمسالك البولية، واجهزة مناظير الجهاز الهضمي، ونعمل على توفير منتجاتنا في جميع مستشفيات مصر، وحالات الطوارئ، وبيئات الرعاية المنزلية، والأدوات المتخصصة التي تستخدم أثناء العناية المركزة والجراحة، والرعاية اللاحقة للعمليات الجراحية ودعم الأمراض المزمنة.",
    "item1Medical": "الآلات الجراحية",
    "item2Medical": "أجهزة التعقيم",
    "item3Medical": "المستلزمات الشخصية",
    "item4Medical": "تجهيز غرف العمليات",

    "foundations": "أهم الأسس في عملنا",
    "foundationHeader": "الولاء",
    "foundationContent": "لوطننا الغالي مصر الذي نسعى لخدمته وتحقيق رفاهيته.",

    "QualityHeader": "الجودة",
    "QualityContent": "تذكرة الوصول إلى أحلامنا وطموحنا.",

    "ResilienceHeader": "المرونة",
    "ResilienceContent": "ثقتنا في أنفسنا تمكننا من تسخير الصعاب لجعلها في متناول الأيدي.",

    "ResponsibilityHeader": "المسؤلية",
    "ResponsibilityContent": "تجاه الوفاء بالتزاماتنا بأعلى معايير الجودة.",


    "backHeader": "شركاتنا",
    "frontHeader": "الشركات",
    "ConstructionHeader": "ايه ام اتش للمقاولات",
    "ConstructionContent": "هي شركة وطنية مصرية تسعي دائما إلى الريادة في مجال المقاولات العامة والتوريدات...",
    "ConstructionTotalContent": "هي شركة وطنية مصرية تسعي دائما إلى الريادة في مجال المقاولات العامة والتوريدات. لقد تخصصت الشركة في أعمال التسويات و الحفر والقطع وأعمال الطرق والرصف والبنية التحتية وأعمال المقاولات العامة والتشطيبات والديكورات . التخصص في أعمال إنشاء وإعداد وتجهيز المباني وأعمال التوريدات العمومية لقطاع البناء والتشييد والتشطيبات والديكورات و الأجهزة الأمنية و أعمال اللاند سكيب والهارد سكيب .الدقة في التنفيذ وسرعة التنفيذ وإحترام الكادر المصري للطرق و البناء بإتباع المواصفات القياسية وقدرة الشركة على تنسيق المواقع و عدم قبول أي عيوب في الأعمال.",
    "AgriculturalHeader": "أيه أم أتش الزراعية",
    "AgriculturalContent": "شركة متخصصة في إدارة المزارع الكبرى بأحدث تكنولوجيا الزراعة، وتقام أحدث مشاريعنا بالتعاون مع القوات المسلحة...",
    "AgriculturalTotalContent": "شركة متخصصة في إدارة المزارع الكبرى بأحدث تكنولوجيا الزراعة، وتقام أحدث مشاريعنا بالتعاون مع القوات المسلحة. تعمل شركة أيه أم أتش الزراعية على استصلاح الأراضي الزراعية، وتوحيد معايير تداول الإنتاج الزراعي لأغراض الاستهلاك في السوق المحلية، والحفاظ على جودة المحاصيل الزراعية لإنتاج غذاء صحي وامن. وقد دخلت الشركة إلى سوق العمل منذ عام 2020، وبدأت مشوارها الزراعي بمشروع هام وضخم وهو استصلاح مزرعة المعاهدة الجديدة ) بمساحة 185",
    "ImportExportHeading": "أيه أم أتش للاستيراد والتصدير",
    "ImportExportContent": "شركة متخصصة في مجال الاستيراد والتصدير تهدف لتحقيق رؤيتنا في دعم الاقتصاد المصرى وزيادة القدرة على تقديم خدمات تجارية دولية متميزة...",
    "ImportExportTotalContent": "شركة متخصصة في مجال الاستيراد والتصدير تهدف لتحقيق رؤيتنا في دعم الاقتصاد المصرى وزيادة القدرة على تقديم خدمات تجارية دولية متميزة.وقد حصلت أيه أم أتش للاستيراد والتصدير على العديد من التوكيلات التجارية كموزع معتمد وحصري لأفضل المنتجات العالمية في العديد من القطاعات.",
    "TechnologyHeading": "أيه أم أتش تكنولوجي",
    "TechnologyContent": "شركة مساهمة مصرية تعمل في مجال الحلول البرمجية الذكية المتكاملة من خلال مجموعة من أفضل مهندسي البرمجيات، وتحت إدارة طامحة ومنفتحة، ونقدم الحلول البرمجية المناسبة لكل ما يتطلبه السوق ...",
    "TechnologyTotalContent": "شركة مساهمة مصرية تعمل في مجال الحلول البرمجية الذكية المتكاملة من خلال مجموعة من أفضل مهندسي البرمجيات، وتحت إدارة طامحة ومنفتحة، ونقدم الحلول البرمجية المناسبة لكل ما يتطلبه السوق . تحرص أيه أم أتش تكنولوجي على تقديم أعلى معايير الجودة لعملائها، وذلك من خلال استخدام أحدث التقنيات العالمية في البرمجة، والتدريب والإدارة، وتتطلع إلى المشاركة في تنفيذ التحول الرقمي وتطبيق مبادئ الحوكمة والشمول المالي في مصر والوطن العربي، وتهدف أيضا إلى منافسة كبرى الشركات العالمية في مجال البرمجيات.",
    "MedicalHeading": "أيه أم أتش الطبية",
    "MedicalContent": "هي إحدى الشركات التي تم إنشائها مؤخرا ضمن \"أيه أم آتش زد انترناشونال جروب\" والتي تتمتع بخبرة كبيرة في مجال أعمال المقاولات والتجارة،..",
    "MedicalTotalContent": "هي إحدى الشركات التي تم إنشائها مؤخرا ضمن \"أيه أم آتش زد انترناشونال جروب\" والتي تتمتع بخبرة كبيرة في مجال أعمال المقاولات والتجارة، ولدينا الآن أفضل الموظفين الموهوبين ذوي الخبرة الكبيرة في منتجات المجال الطبي. لقد بدأنا كمورد للمنتجات الطبية التي تستخدم لمرة واحدة وتتزايد مجموعة منتجاتنا تدريجيا. يمنحنا موقع مصر المتميز الفرصة في تقليل تكلفة الطلب لاننا موجودون في وسط العالم مما يقلل من تكلفة الشحن، كما وقعت مصر العديد من الاتفاقيات التجارية بين العديد من الدول والمناطق التي من شأنها خفض الرسوم الجمركية وتقليل السعر النهائي للمنتجات المطلوبة.",
    "ServiceDetails": "تفاصيل الخدمة",
    "SouthernBinZayedAxis": "مشروع محور بن زايد الجنوبى",
    "project1Content": "",
    "CompanyDetails": "تفاصيل الشركة",
    "ProjectDetails": "تفاصيل المشروع",
    "EgyptFutureDabaaProject": "مشروع مستقبل مصر الضبعة",
    "RoadworksAley": "اعمال الطرق بعاليه ",
    "AhmadiyaStationProject": " مشروع محطة الاحمدية ",
    "Sherbinstationproject": " مشروع محطة شربين ",
    "Road32Project": " مشروع طريق 32 ",
    "BinZayedAxisProject": " مشروع محور بن زايد ",
    "constructionProject": "مشروع بناء",
    "SouthernBinZayedAxisContent": "ومن المرجح أن يكون مشروع محور جنوب بن زايد مبادرة استراتيجية للبنية التحتية أو التطوير الحضري تحمل اسم الشيخ زايد بن سلطان آل نهيان، مما يعكس الجهود المستمرة التي تبذلها المنطقة للتوسع والتحديث.",
    "EgyptFutureDabaaProjectContent": "يشير مشروع الضبعة المستقبلي لمصر إلى محطة الطاقة النووية بالضبعة، وهي مبادرة مهمة واستراتيجية في قطاع الطاقة في مصر. يقع هذا المشروع في منطقة الضبعة بمحافظة مطروح على ساحل البحر الأبيض المتوسط، ويمثل أول مشروع لمصر في مجال الطاقة النووية.",
    "RoadworksAleyContent": "تشير أعمال الطرق في عاليه إلى أنشطة تطوير البنية التحتية وصيانتها في قضاء عاليه الواقع في محافظة جبل لبنان. ومن المرجح أن يتضمن هذا المشروع إنشاء أو توسيع أو إصلاح الطرق وشبكات النقل داخل المنطقة.",
    "AhmadiyaStationProjectContent": "من المرجح أن يشير مشروع محطة الأحمدية إلى تطوير أو ترقية مركز نقل، ربما محطة قطار أو مترو، في منطقة الأحمدية. قد يتضمن هذا المشروع إنشاء محطة جديدة أو تجديد محطة قائمة لخدمة الركاب بشكل أفضل وتحسين الاتصال في المنطقة.",
    "SherbinstationprojectContent": "من المرجح أن يشير مشروع محطة شربين إلى تطوير أو تحسين محطة النقل في شربين، وهي مدينة تقع في محافظة الدقهلية في مصر. وقد يتضمن هذا المشروع إنشاء محطة قطار أو حافلات جديدة أو تجديد وتحديث منشأة قائمة.",
    "Road32ProjectContent": "من المرجح أن يتضمن مشروع الطريق 32 إنشاء أو توسيع أو إعادة تأهيل طريق مهم، يُطلق عليه اسم \"الطريق 32\"، في منطقة معينة. ويركز هذا المشروع على تحسين البنية الأساسية للنقل، وتسهيل تدفق حركة المرور بشكل أكثر سلاسة، وتعزيز الاتصال بين المناطق الرئيسية.",
    "BinZayedAxisProjectContent": "من المرجح أن يشير مشروع محور بن زايد إلى مبادرة كبرى للبنية التحتية تحمل اسم الشيخ زايد بن سلطان آل نهيان، وتهدف إلى إنشاء ممر رئيسي للنقل أو التنمية. ويركز هذا المشروع على بناء أو تحديث طريق أو طريق سريع أو محور حضري مهم يربط بين المناطق أو الأحياء المهمة.",
    "viewmore": "عرض المزيد",

    "ourobjectives": "أهدافنا",
    "Achieve": "كيف نحقق",
    "goal": "أهدافنا",
    "goal1Header": "١. تأسيس شراكات استراتيجية",
    "goal1Content": "بناء شراكات مع الشركات الرائدة في قطاع البناء المحلي والدولي",
    "goal2Header": "٢. رضا العملاء",
    "goal2Content": "تلبية وتجاوز متطلبات العملاء بأعلى المعايير في وقت قياسي",
    "goal3Header": "٣. التكامل في الخدمة الوطنية",
    "goal3Content": "دمج مفهوم الخدمة الوطنية في كافة مشاريع المجموعة المختلفة",
    "goal4Header": "٤. التطوير والنمو",
    "goal4Content": "تحقيق التطور والنمو اللازمين لزيادة تدفق الاستثمار والربحية",
    "circleNumber1": "١",
    "circleNumber2": "٢",
    "circleNumber3": "٣",
    "circleNumber4": "٤",
    "makeRequest": "لطلب",
    "furtherinformation": "المزيد من المعلومات،",
    "socialchannels": "عبر قنواتنا الاجتماعية.",
    "wejust": "نحن بحاجة إلى بضع ساعات فقط!",
    "nomore": "لا يزيد عن يومي عمل منذ استلام التذكرة الخاصة بك",
    "submit": "أرسل رسالة",
    "requiredfield": "هذه الخانة مطلوبه.",

    "obtaining": "للحصول على مزيد من المعلومات، يمكنك التواصل مع موظفينا ذوي الخبرة في مجال تكنولوجيا المعلومات.",

    "available": "نحن متاحون لمدة 8 ساعات يوميًا!",
    "contactto": "اتصل بنا لطلب تحليل وتقييم مفصل لخطتك.",
    "reach": "تواصل معنا الآن!",
    "werun": "نحن ندير جميع أنواع خدمات تكنولوجيا المعلومات التي تضمن ",
    "suc": "نجاحك",
    "let'stalk": "دعنا نتحدث",
    "getinfo": "احصل على المعلومات",
    "ITServices": "خدمات تكنولوجيا المعلومات المصممة لـ",
    "HighlyTailored": "خدمات تصميم وإدارة ودعم تكنولوجيا المعلومات المصممة خصيصًا.",
    "freeconsultation": "استشارة مجانية",
    "howwework": "كيف نعمل",
  },
  "fr": {
    "home": "Accueil",
    "phone": "+20221808809",
    "address": "7 rue Mohamed Mahmoud Ezzat, Hegaz, Le Caire, Égypte",
    "AMHZ": "AMHZ Group",
    "titleContracting": "titleContracting"


  }
}
